const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Flash,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Plugins.Mouse,
		C3.Behaviors.destroy,
		C3.Plugins.Spritefont2,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{Plataforma: 0},
	{Piscar: 0},
	{CentrarEm: 0},
	{Mago: 0},
	{Sólido: 0},
	{blocoembranco1: 0},
	{Teclado: 0},
	{Projétil: 0},
	{diabo: 0},
	{Mouse: 0},
	{DestruirForaDoLayout: 0},
	{magiaheroi: 0},
	{blocoembranco2: 0},
	{blocoembranco3: 0},
	{blocoembranco4: 0},
	{FonteDeSprites: 0},
	{blocoembranco5: 0},
	{blocoembranco6: 0},
	{drag: 0},
	{Fundo: 0},
	{blocoembranco7: 0},
	{blocoembranco8: 0},
	{PlanoDeFundoEmBlocos: 0},
	{botaoinicio: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{gameroversim: 0},
	{gameovernao: 0},
	{Áudio: 0},
	{Âncora: 0},
	{Coracao: 0},
	{chave: 0},
	{barreira: 0},
	{barreira2: 0},
	{barreira3: 0},
	{areaProtegida: 0},
	{Vida: 0},
	{portal: 0},
	{plataforma: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{Fundoparabens: 0},
	{botaoparabens: 0},
	{PortalFase: 0},
	{bloco: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{Texto: 0},
	{Texto2: 0},
	{casasobre: 0},
	{botaosobre: 0},
	{sobreinicio: 0}
];

self.InstanceType = {
	Mago: class extends self.ISpriteInstance {},
	blocoembranco1: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	diabo: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	magiaheroi: class extends self.ISpriteInstance {},
	blocoembranco2: class extends self.ISpriteInstance {},
	blocoembranco3: class extends self.ISpriteInstance {},
	blocoembranco4: class extends self.ISpriteInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	blocoembranco5: class extends self.ISpriteInstance {},
	blocoembranco6: class extends self.ISpriteInstance {},
	drag: class extends self.ISpriteInstance {},
	Fundo: class extends self.ISpriteInstance {},
	blocoembranco7: class extends self.ISpriteInstance {},
	blocoembranco8: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	botaoinicio: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	gameroversim: class extends self.ISpriteInstance {},
	gameovernao: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Coracao: class extends self.ISpriteInstance {},
	chave: class extends self.ISpriteInstance {},
	barreira: class extends self.ISpriteInstance {},
	barreira2: class extends self.ISpriteInstance {},
	barreira3: class extends self.ISpriteInstance {},
	areaProtegida: class extends self.ISpriteInstance {},
	Vida: class extends self.ITextInstance {},
	portal: class extends self.ISpriteInstance {},
	plataforma: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	Fundoparabens: class extends self.ISpriteInstance {},
	botaoparabens: class extends self.ISpriteInstance {},
	PortalFase: class extends self.ISpriteInstance {},
	bloco: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	Texto: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	casasobre: class extends self.ISpriteInstance {},
	botaosobre: class extends self.ISpriteInstance {},
	sobreinicio: class extends self.ISpriteInstance {}
}